Made Major semantic changes to HTML and CSS
emasdev/smithemas_youtube_webpage pull request #4
Opened 2020-03-25 15:53 UTC by SmithVyne

We made major semantic changes and validated both HTML and CSS. This webpage is ready for production.

2020-03-25 18:12 UTC, majovanilla requested changes
Hey team!

## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.

- Always remember to activate your repo in Stickler. I cannot see your linters working!! You must include the stylelint file in your repo.

- Improve your Readme file. It should be descriptive of the project. Here's a great [template](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) I strongly recommend you to use.

- Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- **Do not** close the original Pull Request. When you make the changes in a pull request you need to submit the same link again. That way we can follow the history of your commits, previous reviews and changes...all until your PR is approved.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Improve the section below the main video. Add some padding to the left to make it look like the original page and separate the buttons of the right using some margin between them.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-25 18:12 UTC, majovanilla commented on index.html
> +<!DOCTYPE html>
- [x] Check your file against the validator. You have one error.
![Screenshot from 2020-03-25 11-55-15](https://user-images.githubusercontent.com/51926937/77569266-8e992000-6e8f-11ea-90aa-e2930dbe3a3c.png)

2020-03-25 18:12 UTC, majovanilla commented on .gitignore
> +stylelint.config.js
- [x] Don't include your styling in the gitignore. You want it to be in your repo so Stickler can check your linters.

2020-03-25 18:12 UTC, majovanilla commented on style.css
> +}
- [ ] The previous TSE made an observation here and will like to clarify it. When you have classes, there is not necessary to create the "path" that leads to the element you want to style. In this code, are you saying that you want the elements with the vide, desc, details and buttons classes to have the text aligned to the right? or are you saying that you want the text inside the buttons to be aligned to the right?

If the answer is yes to the first question, you are doing it right. If your answer is no, then you just need the buttons class in there and delete the rest. That's what classes are for.

You would need to specify such path when using tags, for example, when you want to style the main > div > buttons.

Make sure you are actually styling what you want and if necessary, make the changes in all cases.

2020-03-25 21:44 UTC, men32z commented
Hi!
Congratulations!
The code is clean and organized, you have made almost all the changes but still missing this one. 

"Always remember to activate your repo in Stickler. I cannot see your linters working!! You must include the stylelint file in your repo."

the file .stickler.yml is still missing, you [can  see here](https://github.com/microverseinc/linters-config/tree/master/css) how to configure stickler in your project, if you have questions you can reach me in slack. 
Happy Coding! 🤓

- Luis Preza

Status: Request changes.

2020-03-25 21:51 UTC, men32z requested changes
Hi!
Congratulations!
The code is clean and organized, you have made almost all the changes but still missing this one.

"Always remember to activate your repo in Stickler. I cannot see your linters working!! You must include the stylelint file in your repo."

the file .stickler.yml is still missing, you [can see here ](https://github.com/microverseinc/linters-config/tree/master/css)how to configure stickler in your project, if you have questions you can reach me in slack.
Happy Coding! 🤓

Luis Preza

Status: Request changes.

2020-03-26 18:00 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

2020-03-26 18:11 UTC, mikenath223 approved these changes
### Nice Job Team 👏👏👏

It's nice that you have worked on aspects of your projects mentioned in previous reviews. 👍

STATUS: APPROVED ✅

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-03-26 19:14 UTC, merged